import QtQuick
import QtQuick.Window
import QtQuick.Layouts
import QtQuick.Dialogs
import QtQuick.Controls
import QtQuick.Controls.Material

// 主页面的底层layer，这里提及的内容能够为跨文件访问提供支撑. 具体的功能函数，都在这里写实现。
Page {
    id: homePage
    anchors.fill: parent

    // 用在 Example_Item 里面，传过来需要提前显式声明
    property StackView stackViewPass

    // 默认不进入编辑模式和设置模式
    property bool editMode: false
    property bool settingsMode: false

    Item {
        anchors.fill: parent

        Home_HeaderBar {
            id: header
            visible: !homePage.settingsMode // make invisible when entering settings_page
            editMode: homePage.editMode // upcast the edit mode to the homepage
            onEditModeRequested: function (nextEditModeStatus) {
                homePage.editMode = nextEditModeStatus;
            }
            // pass sorting signal, pass the void sorting functions from item.cpp
            onSortRequested: function (sortMode) {
                if (sortMode === "dateAsc") {
                    itemListModel.sortByDateAscending();
                } else if (sortMode === "dateDesc") {
                    itemListModel.sortByDateDescending();
                } else if (sortMode === "nameAsc") {
                    itemListModel.sortByNameAscending();
                } else if (sortMode === "nameDesc") {
                    itemListModel.sortByNameDescending();
                }
            }
        }

        Home_NaviBar {
            id: naviBar
            addItemDialog: addItemDialog
            showAddButton: !homePage.settingsMode // make invisible when entering settings_page

            // function to enter settings_page, meanwhile entering settings mode
            onPageRequested: function (pageName) {
                homePage.settingsMode = (pageName === "settings");
                if (homePage.settingsMode) {
                    homePage.editMode = false; // validation ensure
                }
            }
        }

        Home_AddItemDialog {
            id: addItemDialog
            onAddItemRequested: function (itemName, itemExpense, purchaseDateText) {
                const expenseInUsd = currencyManager.parseAmountToUSD(itemExpense);
                if (expenseInUsd <= 0
                        || !itemListModel.addItem(itemName, expenseInUsd.toFixed(2), purchaseDateText)) {
                    console.log("[Error] Failed to add item from AddItemDialog");

                    // msgbox indicating error input
                    addItemDialog.open();
                }
            }
        }

        Home_ItemList {
            id: homeItemList
            visible: !homePage.settingsMode // make invisible when entering settings_page
            anchors.top: header.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.bottom: naviBar.top
            stackViewPass: homePage.stackViewPass
            editMode: homePage.editMode
        }

        Settings_Page {
            id: settingsPage
            visible: homePage.settingsMode
            anchors.fill: homeItemList
        }

        // 用来检测添加对话框的输入错误
        MessageDialog {
            id: addItemErrorDialog
            title: qsTr("Input Error")
            text: qsTr("Please type in valid item name, item expense, and purchase date.")
            buttons: MessageDialog.Ok
        }

        // THIS WAS JUST FOR FUNCTION TEST AND WILL NOT BE INCLUDED IN THE RELEASE VERSION
        Example_Item {
            id: exampleItem
            visible: false
            /* Note: this explanation was generated by Codex and was stored here for me to understand clearly.

            stackViewPass: homePage.stackViewPass 不是“继承”，而是属性赋值/绑定：把外面传进来的 stackView 实例引用再转交给子组件。

            具体链路应是：
            Main.qml 把自己的 stackView 传给首页：initialItem: Home_Page { stackViewPass: stackView }
            Home_Page.qml 声明 property StackView stackViewPass 用来接收；内部再写 Example_Item { stackViewPass: homePage.stackViewPass }，等于把同一个引用继续传下去。
            这样 Example_Item 和后续 Detail_Page 都拿到的是同一个 StackView 对象，用它 push/pop。
            所以这行的意思就是“把我收到的 stackViewPass 再传给 Example_Item”，没有自我继承，只有引用转交。
            */
            stackViewPass: homePage.stackViewPass // 被Main.qml中是StackView创建，传到homePage，再传给Example_Item 和 Detail_Page.这样 Example_Item 和后续 Detail_Page 都拿到的是同一个 StackView 对象，用它 push/pop。

        }
    }
}
