import QtQuick
import QtQuick.Window
import QtQuick.Layouts
import QtQuick.Controls
import QtQuick.Controls.Material

Button {
    id: exampleItem
    y: 80
    width: parent.width / 2

    text: "example item"

    property StackView stackViewPass

    onClicked: {
        console.log("[User Click] Example Item Button Clicked");

        // 第三层继承，从Homepage传过来，然后再带着Detail_Page这个实例，推三层回去。这样Detail_Page的stackViewPass 就指向最初的 StackView
        // exampleItem.stackViewPass.push("Detail_Page.qml"); // go to detail page

        // Note: this lambda expression was generated by Codex
        /* Note: this explanation was generated by Codex and was stored here for me to understand clearly.

        因为这一段把同一个 StackView 实例在“push 时”显式传给新创建的 Detail_Page，它的 stackViewPass 属性才有值，Back 按钮才能调用 pop：

        stackViewPass.push(...) 第二个参数是属性初始化对象，等价于创建 Detail_Page { stackViewPass: stackViewPass }。否则 Detail_Page 里 stackViewPass 还是 undefined，pop 调用直接报 ReferenceError。
        Qt.resolvedUrl("Detail_Page.qml") 只是把相对路径变成绝对 URL，防止路径解析问题，关键还是把 { stackViewPass: stackViewPass } 传进去。
        整个链路：Main.qml 把 stackView 传给 Home_Page → Home_Page 传给 Example_Item → Example_Item push 详情页时再传给 Detail_Page。这样所有页面用的是同一个栈实例。
        */
        stackViewPass.push(Qt.resolvedUrl("Detail_Page.qml"), {
            stackViewPass: exampleItem.stackViewPass
        });
    }
}
